{"name": "Создание курьера с пустыми данными с возвращением ошибки-", "status": "passed", "start": 1725392747954, "stop": 1725392748104, "uuid": "72b9bad7-c62c-4c77-b93a-09dbf54993d2", "historyId": "a7d9eb5738d71f5d2fed387988a89add", "testCaseId": "a7d9eb5738d71f5d2fed387988a89add", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_without_date_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-ECR6Q27"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}