{"name": "Вход курьера без пароля с возвращением ошибки-", "status": "passed", "start": 1725392775922, "stop": 1725392776347, "uuid": "fcfbbfc5-8250-4e09-82b3-c3a4c4f0932c", "historyId": "0b4bb7c7863ffde14ddeb8e810efce61", "testCaseId": "0b4bb7c7863ffde14ddeb8e810efce61", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_without_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-ECR6Q27"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}