{"name": "Вход курьера с несуществующими данными и возвращением ошибки-", "status": "passed", "start": 1725392777108, "stop": 1725392777436, "uuid": "d492244d-b2e3-4e02-b382-68111639f297", "historyId": "c6d8db22233328ea48c0d555312a713e", "testCaseId": "c6d8db22233328ea48c0d555312a713e", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_without_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-ECR6Q27"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}